version: '3.8'

services:
  app:
    build:
      context: https://github.com/hrtsv/TempMan.git#main
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    restart: unless-stopped
    devices:
      - /dev/ipmi0:/dev/ipmi0
      - /dev/nvidia0:/dev/nvidia0
    privileged: true

networks:
  default:
    name: tempman_network
